name: branch-filter
on:
  push: 
    branches:
    - dev
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
        - name: github context print 2
          run: echo '${{ toJSON(github) }}'