name: tag-filter
on:
    push: 
        tags: 
            'v[0-9]+.[0-9]+.[0-9]+' # v1.0.0 or v1.1.1
jobs:
    tag-filter:
        runs-on: ubuntu-latest
        steps:
        - name: echo
          run: echo hello

# git tag v1.0.0
# git push origin v1.0.0