name: checkout
on: workflow_dispatch
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: read
          run: cat README.md