name: timeout
on: push
jobs:
    timeout:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
        - name: loop
          run: |
            while true; do
              echo "sleep 10" 
              sleep 10
            done