name: if-step
on:
    push:
    workflow_dispatch: 

jobs:
    job1:
        runs-on: ubuntu-latest 
        steps:
        - name: get event name
          if: github.event_name == 'workflow_dispatch'
          run: echo ${{ github.event_name }}
        - name: get event name
          if: github.event_name == 'push'
          run: echo ${{ github.event_name }}