name: matrix
on: push
jobs:
    get-matrix:
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest] 
        runs-on: ${{ matrix.os }}
        steps:
        - name: check matrix
          run: | 
            echo ${{ matrix.os }}