name: output
on: push

jobs:
    create-output:
        runs-on: ubuntu-latest
        steps:
        - name: echo output
          id: echo_output
          run: |
            echo "testk=testv" >> $GITHUB_OUTPUT
        - name: check output
          run: |
            echo ${{ steps.echo_output.outputs.testk }}
