name: pull-request-workflow
on: 
    pull_request:
        types: [opened]
jobs:
    pull-req-job:
        runs-on: ubuntu-latest
        steps: 
        - name: step1
          run: echo hello world
        - name: step2
          run: |
            echo hello world2
            echo hello world3
            echo hello world4