name: push-workflow
on: push

jobs:
    push-job:
        runs-on: ubuntu-latest
        steps: 
        - name: step1
          run: echo hello world
        - name: step2
          run: |
            echo hello world2
            echo hello world3

# name: workflow의 이름을 지정합니다. 이는 선택 사항입니다.
# on: workflow가 실행될 이벤트를 지정합니다. 예를 들어, push나 pull request와 같은 이벤트를 지정할 수 있습니다.
# jobs: workflow에서 실행할 작업을 정의합니다. 각 작업은 병렬로 실행될 수 있으며, 여러 단계로 구성됩니다.
    # jobs.<job_id>.name: 작업의 이름을 지정합니다.
    # jobs.<job_id>.runs-on: 작업이 실행될 환경을 지정합니다. 예를 들어, Ubuntu, macOS, Windows 등이 될 수 있습니다.
    # jobs.<job_id>.steps: 작업에서 수행할 단계를 정의합니다. 각 단계는 실행할 명령을 지정하고, 필요한 경우 환경을 설정할 수 있습니다.