name: timeout
on: push
jobs:
    timeout:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
        - name: loop
          run: | 
            count=0
            while true; do
              echo "seconds: $count"
              ((count++))
              sleep 1
            done